#!/bin/bash
rm -rf classes
mkdir classes

CP="classes:$(lein classpath):examples/websocket/"

java -cp "$CP" \
    clojure.main -m pi.main



    # -Xdebug -Xrunjdwp:transport=dt_socket,address=9092,server=y,suspend=n \
